// Copyright 2023 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i anime_image.png -f pal256`

#pragma once

#include <qp.h>

extern const uint32_t gfx_anime_image_length;
extern const uint8_t  gfx_anime_image[55221];
